### 数组类型

In [2]:
import numpy as np

In [3]:
tang_array = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(tang_array.dtype)
print(tang_array.nbytes)

float32
20


In [4]:
tang_array = np.array([1, 10, 3, 5.1, 'str'], dtype=np.object)
print(tang_array)
print(tang_array * 2)

[1 10 3 5.1 'str']
[2 20 6 10.2 'strstr']


In [6]:
tang_array = np.array([1, 2, 3, 4, 5])
print(np.asarray(tang_array, dtype=np.float32))
print(tang_array)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [8]:
print(tang_array.astype(np.float32))

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


### 数值计算

In [11]:
tang_array = np.array([[1, 2, 3],
                       [4, 5, 6]])


In [12]:
print(np.sum(tang_array))

21


In [13]:
print(tang_array.sum())

21


In [14]:
print(np.sum(tang_array, axis=0))

[5 7 9]


In [15]:
print(np.sum(tang_array, axis=1))

[ 6 15]


In [16]:
print(np.sum(tang_array, axis=1))

[ 6 15]


In [17]:
print(tang_array.sum(axis=0))

[5 7 9]


In [18]:
print(tang_array.sum(axis=1))

[ 6 15]


In [19]:
print(tang_array.sum(axis=-1))

[ 6 15]


In [20]:
print(tang_array.prod())

720


In [21]:
print(tang_array.prod(axis=0))

[ 4 10 18]


In [22]:
print(tang_array.prod(axis=1))

[  6 120]


In [23]:
print(tang_array.prod(axis=-1))

[  6 120]


In [24]:
print(tang_array.min())

1


In [25]:
print(tang_array.min(axis=0))

[1 2 3]


In [26]:
print(tang_array.min(axis=1))

[1 4]


In [27]:
print(tang_array.min(axis=-1))

[1 4]


In [28]:
print(tang_array.max())

6


In [29]:
print(tang_array.argmin())

0


In [30]:
print(tang_array.argmin(axis=0))

[0 0 0]


In [31]:
print(tang_array.argmin(axis=1))

[0 0]


In [32]:
print(tang_array.mean())

3.5


In [33]:
print(tang_array.mean(axis=0))

[2.5 3.5 4.5]


In [34]:
print(tang_array.mean(axis=1))

[2. 5.]


In [35]:
# std标准差
print(tang_array.std())
print(tang_array.std(axis=1))

1.707825127659933
[0.81649658 0.81649658]


In [36]:
# 方差
print(tang_array.var())
print(tang_array.var(axis=1))

2.9166666666666665
[0.66666667 0.66666667]


In [37]:
print(tang_array.clip(2, 4))

[[2 2 3]
 [4 4 4]]


In [38]:
tang_array = np.array([1.2, 3.334, 2.2222,
                       2.1121, 3.222, 3.356])

print(tang_array.round())
print(tang_array.round(decimals=1))

[1. 3. 2. 2. 3. 3.]
[1.2 3.3 2.2 2.1 3.2 3.4]


### 数组形状

In [48]:
tang_array = np.arange(10)
print(tang_array)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
print(tang_array.shape)

(10,)


In [50]:
tang_array.shape = 2, 5
print(tang_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [51]:
print(tang_array.reshape(1, 10))

[[0 1 2 3 4 5 6 7 8 9]]


In [52]:
tang_array = np.arange(10)
print(tang_array.shape)

(10,)


In [53]:
tang_array = tang_array[:, np.newaxis]
print(tang_array)
print(tang_array.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [54]:
tang_array = tang_array[:, np.newaxis, np.newaxis]
# print(tang_array)
print(tang_array.shape)

(10, 1, 1, 1)


In [56]:
tang_array = tang_array.squeeze()
print(tang_array)
print(tang_array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [57]:
tang_array.shape = 2, 5
print(tang_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [58]:
print(tang_array.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [59]:
print(tang_array.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [60]:
print(tang_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### 数组的连接

In [61]:
a = np.array([[123, 456, 789], [321, 432, 654]])
print(a)

[[123 456 789]
 [321 432 654]]


In [62]:
b = np.array([[1234, 4526, 9], [31, 42, 65]])
print(b)

[[1234 4526    9]
 [  31   42   65]]


In [63]:
c = np.concatenate((a, b))
print(c)

[[ 123  456  789]
 [ 321  432  654]
 [1234 4526    9]
 [  31   42   65]]


In [64]:
c = np.concatenate((a, b), axis=0)
print(c)

[[ 123  456  789]
 [ 321  432  654]
 [1234 4526    9]
 [  31   42   65]]


In [65]:
c = np.concatenate((a, b), axis=1)
print(c)
print(c.shape)

[[ 123  456  789 1234 4526    9]
 [ 321  432  654   31   42   65]]
(2, 6)


In [66]:
print(np.vstack((a, b)))

[[ 123  456  789]
 [ 321  432  654]
 [1234 4526    9]
 [  31   42   65]]


In [67]:
print(np.hstack((a, b)))

[[ 123  456  789 1234 4526    9]
 [ 321  432  654   31   42   65]]


In [68]:
print(a)

[[123 456 789]
 [321 432 654]]


In [69]:
print(a.flatten())

[123 456 789 321 432 654]


In [70]:
print(a.ravel())

[123 456 789 321 432 654]
