### 常用数组生成函数

In [1]:
import numpy as np

In [2]:
print(np.zeros(3))

[0. 0. 0.]


In [4]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(np.ones((3, 3)) * 8)

[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [9]:
print(np.ones((3, 3), dtype=np.float32))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a = np.empty(6)
print(a)

[0. 0. 0. 0. 0. 0.]


In [11]:
print(a.shape)

(6,)


In [12]:
a.fill(1)
print(a)

[1. 1. 1. 1. 1. 1.]


In [14]:
tang_array = np.array([1, 2, 3])
print(np.zeros_like(tang_array))
print(np.ones_like(tang_array))

[0 0 0]
[1 1 1]


In [15]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 运算

In [16]:
import numpy as np

In [17]:
x = np.array([5, 5])
y = np.array([2, 2])

In [18]:
print(np.multiply(x, y))

[10 10]


In [19]:
print(np.dot(x, y))

20


In [22]:
x.shape = 2, 1
print(x)

[[5]
 [5]]


In [23]:
y.shape = 1, 2
print(x.shape, y.shape)

(2, 1) (1, 2)


In [24]:
print(np.dot(x, y))
print(np.dot(y, x))

[[10 10]
 [10 10]]
[[20]]


In [25]:
x = np.array([1, 1, 1])
y = np.array([[1, 2, 3], [4, 5, 6]])

In [26]:
print(x * y)

[[1 2 3]
 [4 5 6]]


In [28]:
x = np.array([1, 1, 1])
y = np.array([1, 1, 1])
print(x == y)

[ True  True  True]


In [29]:
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x, y))

[ True  True  True]
[ True  True  True]
[0 0 0]
