# 使用numpy读写

In [5]:
import numpy as np

In [6]:
%%writefile tang.txt
1 2 3 4 5 6
2 3 4 5 6 7

Overwriting tang.txt


In [7]:
data = []

with open("tang.txt") as f:
    for line in f:
        fileds = line.split()
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)

data = np.array(data)
print(data)      

[[1. 2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6. 7.]]


In [8]:
data = np.loadtxt('tang.txt')
print(data)

[[1. 2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6. 7.]]


In [9]:
%%writefile tang2.txt
a,b,c,d,e,f
1,2,3,4,5,6
2,3,4,5,6,7

Writing tang2.txt


In [10]:
data = np.loadtxt('tang2.txt',delimiter=',',skiprows=1)
print(data)

[[1. 2. 3. 4. 5. 6.]
 [2. 3. 4. 5. 6. 7.]]


* 'xxx.xxx'：路径最好放到和代码一起
* skiprows：去掉几行
* delimiter= ：分隔符
* usecols=（0，1，4）：指定使用哪几列

In [13]:
tang_array = np.array([[1,2,3],[4,5,6]])
np.savetxt('tang3.txt',tang_array)

In [14]:
np.savetxt('tang3.txt',tang_array,fmt='%d')

In [15]:
np.savetxt('tang3.txt',tang_array,fmt='%d',delimiter=',')

In [16]:
np.savetxt('tang3.txt',tang_array,fmt='%.2f',delimiter=',')

# 读写array结构

In [17]:
tang_array = np.array([[1,2,3],[4,5,6]])
np.save('tang_array.npy',tang_array)

In [18]:
tang = np.load('tang_array.npy')
print(tang)

[[1 2 3]
 [4 5 6]]


In [19]:
tang_array2 = np.arange(10)
print(tang_array2)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
np.savez('tang.npz',a=tang_array,b=tang_array2)

In [21]:
data = np.load('tang.npz')

In [26]:
data.keys()
print(data.keys())

['a', 'b']


In [27]:
print(data['a'])

[[1 2 3]
 [4 5 6]]


In [28]:
print(data['b'])

[0 1 2 3 4 5 6 7 8 9]
